### PR TITLE
Secondary sorting by user id

### PR DESCRIPTION
**Pull request by Gspin96**
Fixes the sorting within groups of users with the same amount of points, which didn't appear to make any sense and would change in a seemingly random fashion on cache expires.

### CODE REVIEW

**Comment by JDGrimes** [comment]
Thank you for the patch, @Gspin96 !

I guess sorting by `ID` secondarily does make sense here, just to keep the order consistent. So I'll be sure to merge this before the next update is released.

Eventually, maybe it would be a good idea to actually group the users together as being in the same position (e.g., two users could share third place, instead of one being in third and one being in forth). But that would be for a separate issue sometime in the future.

**Comment by JDGrimes** [comment]
Do not mind the Travis build failures—they are unrelated.

**Comment by Gspin96** [comment]
Thank you!

Probably it'd be better to make grouping optional, as some (me) may like their rankings free of ties.

**Comment by JDGrimes** [comment]
OK, that sounds like a good idea.

**Comment by JDGrimes** [comment]
Thanks again for the PR @Gspin96! My apologies that it took so long to get merged—I was waiting to see if I would release a 2.3.1, or just make this part of 2.4.0. In the end, no 2.3.1 was deemed necessary, so this will be a part of 2.4.0, which will be released in the next couple of weeks.

**Pull request closed without merging**
